logging.level.ru.yandex.practicum=TRACE
grpc.server.port=59091
kafka.consumer.group-id=collector.group
kafka.consumer.client-id=collector.client
kafka.bootstrap-servers=localhost:9092
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer