kafka.bootstrap-servers=localhost:9092
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
kafka.consumer.group-id=sensorEvent.group.id
kafka.consumer.client-id=sensorEvent.client