spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
        - id: shopping_store_service_route
          uri: lb://shopping-store
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: NOT_FOUND
                exceptions:
                  - ru.yandex.practicum.interaction-api.store.exception.ProductNotFoundException
                methods: GET, POST, PUT
          predicates:
            - Path=/shopping-store/**
        - id: warehouse_service_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
        - id: order_service_route
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: delivery_service_route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
        - id: payment_service_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
      default-filters:
          - PrefixPath=/api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG