spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: shopping_cart_service_route
          uri: lb://shopping-cart
          predicates:
            - Path=/shopping-cart/**
      default-filters:
          - PrefixPath=/api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG