#GRPC \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438
grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.enableKeepAlive=true
grpc.client.hub-router.keepAliveWithoutCalls=true
grpc.client.hub-router.negotiationType=plaintext

#Data Base \u043D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6541/analyzer_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Kafka
kafka.consumer.client-id=analyzer.client
kafka.consumer.group-id=analyzer.group
kafka.topic.telemetry.sensors=telemetry.sensors.v1
kafka.topic.telemetry.hubs=telemetry.hubs.v1
kafka.topic.telemetry.snapshots=telemetry.snapshots.v1
kafka.bootstrap-servers=localhost:9092
kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
kafka.consumer.value-deserializer=ru.yandex.practicum.kafka.deserializer.HubEventDeserializer