logging:
  level:
    ru:
      yandex:
        practicum: TRACE

grpc:
  server:
    port: 59091

kafka:
  consumer:
    group-id: collector.group
    client-id: collector.client
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
  bootstrap-servers: localhost:9092
  topic:
    telemetry:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1
      snapshots: telemetry.snapshots.v1
