grpc:
  client:
    hub-router:
      address: 'discovery:///hub-router'

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6541/analyzer_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  consumer:
    client-id: analyzer.client
    group-id: analyzer.group
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
  topic:
    telemetry:
      sensors: telemetry.sensors.v1
      hubs: telemetry.hubs.v1
      snapshots: telemetry.snapshots.v1
  bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
